name: PR

on:
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write
  security-events: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - name: Build
        run: dotnet fsi ./build.fsx

      - name: Run Analyzers
        run: dotnet msbuild /t:AnalyzeFSharpProject /p:Configuration=Release
        continue-on-error: true

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ./reports